export default {
    SET_CANVAS_DIMENSIONS: "SET_CANVAS_DIMENSIONS",
    SET_CANVAS_MAX_DIMENSIONS: "SET_CANVAS_MAX_DIMENSIONS",
    SET_BACKGROUND_IMAGE: "SET_BACKGROUND_IMAGE",
    SET_SHOW_IMAGE_OVERLAY: "SET_SHOW_IMAGE_OVERLAY",
}